### ISSUE TITLE
pman mangles config file

### ISSUE THREAD

**Issue by rdb** [Moguri/pman#29]
Every time I run `pman run`, it appears to mangle my `.pman` file, changing this:
```toml
[build]
converters = ["native2bam", "blend2bam"]
```
to this:
```toml
[build]
converters = [ "native2bam", "blend2bam",]
```

This happens on Windows.  This is a low priority issue for me.
